/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e225406;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GirlFrendTest {
    @Test 
    
    void marriageTest() {
        int defaultLove = 30;
        GirlFrend demoGirlfrend = new GirlFrend("はなこ", defaultLove, false);
        
        demoGirlfrend.doPresent(demoGirlfrend);

        assertEquals(demoGirlfrend.getLove(), 0);
        assertEquals(demoGirlfrend.getMarriage(), false);
        /**
        * doPresentがしっかり愛ポイントを減らしているかのテスト
        * proposeしていないときはmarriageがfalseかのテスト
        */

        demoGirlfrend.propose(demoGirlfrend);

        assertEquals(demoGirlfrend.getMarriage(), true);
        /**
         * proposeが成功した後はmarriageがtrueかのテスト
         */
    }
}
